config:
  name:
    isRequired: 1
    type: string
    defaultValue: temp
    description: 'Name for project identification'
    isHidden: 1
environ:
  API_KEY:
    isRequired: 0
    type: string
    description: 'API key for using Gemini'
    immutable: 0
  AWS_BUCKET_NAME:
    isRequired: 1
    type: string
    description: 'AWS bucket name'
  VITE_API_URL:
    isRequired: 1
    type: string
    description: 'API URI deployed on AWS Lambda'
    value: '@backend/output.endpoint'