service: template-api

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}
    APP_NAME: ${env:APP_NAME, 'template-api'}

functions:
  hello:
    handler: src/handlers/hello.handler
    timeout: 30
    events:
      - http:
          path: /hello
          method: get
          cors: true
  blogTitleGenerator:
    handler: src/handlers/blog-title-generator.handler
    timeout: 30
    events:
      - http:
          path: /blog-title-generator
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-esbuild

custom:
  serverless-offline:
    httpPort: 4000
    host: 0.0.0.0
    lambdaTimeout: 30000
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    format: cjs
    target: node22
    platform: node
    packager: pnpm
